export const products = [
  {
    id: 1,
    name: "Royal Cheese Burger with extra fries",
    description: "1 McChicken™, 1 French Fries, 1 Drink",
    price: 120,
    currency: "GBP",
    type: "burgers",
    image: "./assets/burger-1.png",
  },
  {
    id: 2,
    name: "The classics for 3",
    description: "3 McChicken™, 3 French Fries, 3 Drinks",
    price: 360,
    currency: "GBP",
    type: "burgers",
    image: "./assets/burger.png",
  },
  {
    id: 3,
    name: "The classics for 4",
    description: "4 McChicken™, 4 French Fries, 4 Drinks",
    price: 480,
    currency: "GBP",
    type: "burgers",
    image: "./assets/burger.png",
  },
  {
    id: 4,
    name: "Vegetarian Burger",
    description: "1 Veggie Burger, 1 French Fries, 1 Drink",
    price: 100,
    currency: "GBP",
    type: "burgers",
    image: "./assets/burger-1.png",
  },
  {
    id: 5,
    name: "Standard Fries",
    description: "Medium French Fries",
    price: 30,
    currency: "GBP",
    type: "fries",
    image: "./assets/fries-1.png",
  },
  {
    id: 6,
    name: "Large Fries",
    description: "Large French Fries",
    price: 50,
    currency: "GBP",
    type: "fries",
    image: "./assets/fries-1.png",
  },
  {
    id: 7,
    name: "Coca Cola",
    description: "Medium Coca Cola",
    price: 20,
    currency: "GBP",
    type: "cold drinks",
    image: "./assets/drink-1.png",
  },
  {
    id: 8,
    name: "Fanta",
    description: "Medium Fanta",
    price: 20,
    currency: "GBP",
    type: "cold drinks",
    image: "./assets/drink-2.png",
  },
];

export const reviews = [
  {
    id: 1,
    name: "St Glx",
    location: "South London",
    date: "24th September, 2023",
    rating: 5,
    image: "./assets/profile-pic.png",
    text: "The positive aspect was undoubtedly the efficiency of the service. The queue moved quickly, the staff was friendly, and the food was hot and well-packaged.",
  },
  {
    id: 2,
    name: "St Glx",
    location: "South London",
    date: "24th September, 2023",
    rating: 5,
    image: "./assets/profile-pic.png",
    text: "The positive aspect was undoubtedly the efficiency of the service. The queue moved quickly, the staff was friendly, and the food was hot and well-packaged.",
  },
  {
    id: 3,
    name: "St Glx",
    location: "South London",
    date: "24th September, 2023",
    rating: 5,
    image: "./assets/profile-pic.png",
    text: "The positive aspect was undoubtedly the efficiency of the service. The queue moved quickly, the staff was friendly, and the food was hot and well-packaged.",
  },
];

export const similarRestaurants = [
  { id: 1, name: "McDonald's London", image: "./assets/mac.png" },
  { id: 2, name: "Papa Johns", image: "./assets/papa-johns.png" },
  { id: 3, name: "KFC West London", image: "./assets/kfc.png" },
  { id: 4, name: "Texas Chicken", image: "./assets/texas.png" },
  { id: 5, name: "Burger King", image: "./assets/burger-king.png" },
  { id: 6, name: "Shaurma 1", image: "./assets/shaurma.png" },
];
