/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TalhaNFT } from './TalhaNFT.js';
export * as factories from './factories/index.js';
export { TalhaNFT__factory } from './factories/TalhaNFT__factory.js';